import streamlit as st

import numpy as np

st.title('Abbreviation Generator')
st.caption('A Small Language Model for Abbreviation Generation by Jose Cortes')

# st.divider()
# st.header('Abbreviation Generator')
text_input = st.text_input('Enter text and press the button', max_chars=20, key='abv_text_input', placeholder='Enter text here... EX: The United States, Hello World, etc.')

import time
import requests

input_words = ''
dict_abv = ''
gen_abv = ''

if st.button('Generate Abbreviations'):
    stateUnfinished = True
    url = 'https://djinfrontapi.herokuapp.com/abr/generate?input_words={}'.format(text_input)
    response = requests.get(url)
    
    with st.spinner('Generating Abbreviations...'):
        while stateUnfinished:
                url = 'https://djinfrontapi.herokuapp.com/abr/aquire?input_words={}'.format(text_input)
                response = requests.get(url).json()
                input_words = ', '.join(response['input_words'])
                dict_abv = ', '.join(response['dict_abv'])
                gen_abv = ', '.join(response['gen_abv'])
                statearray = np.array([state == 'Done' for state in response['state']])
                stateUnfinished = np.sum(statearray) != len(statearray)
                time.sleep(1)
    
st.markdown("""**Input Text**: {}  
            **Oxford Abbreviations**: {}  
            **Generated Abbreviations**: {}""".format(input_words, dict_abv, gen_abv))

st.markdown("""
            **Instructions**: Write a text in the text box and press the button to generate the abbreviations.  
            **Format**: word1, word2, word3, etc. (use comma to separate words of normal characters)  
            **Example**: abridged, hello yall
            """)  
st.divider()
st.header('About')
st.markdown("""
The Abbreviation Generator is a tool to generate abbreviations for a given text.  
It returns the Abbreviations from the Oxford Abbreviations Dictionary if available.  
Then it generates the Abbreviations generated by the model.
""")

st.subheader('Data')

st.markdown("""
            Trained Abbreviations - [Oxford Abbreviations](https://www.oxfordreference.com/view/10.1093/acref/9780199203128.001.0001/acref-9780199203128)
            """)

st.subheader('Model')

st.markdown("""
            Github link for the model - [AbbreviationGenerator](https://github.com/JoseACortes/AbbreviationGenerator)
            """)

